# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotting.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Plotting(object):
    def setupUi(self, Plotting):
        Plotting.setObjectName("Plotting")
        Plotting.resize(629, 542)
        self.centralwidget = QtWidgets.QWidget(Plotting)
        self.centralwidget.setObjectName("centralwidget")
        self.GraphicsView = PlotWidget(self.centralwidget)
        self.GraphicsView.setGeometry(QtCore.QRect(0, 0, 631, 381))
        self.GraphicsView.setObjectName("GraphicsView")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(0, 430, 631, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(460, 380, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        Plotting.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Plotting)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 629, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        Plotting.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Plotting)
        self.statusbar.setObjectName("statusbar")
        Plotting.setStatusBar(self.statusbar)
        self.action_3 = QtWidgets.QAction(Plotting)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(Plotting)
        self.action_4.setObjectName("action_4")
        self.action_6 = QtWidgets.QAction(Plotting)
        self.action_6.setObjectName("action_6")
        self.menu.addSeparator()
        self.menu.addAction(self.action_3)
        self.menu.addSeparator()
        self.menu.addAction(self.action_4)
        self.menu.addSeparator()
        self.menu.addAction(self.action_6)
        self.menu.addSeparator()
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Plotting)
        QtCore.QMetaObject.connectSlotsByName(Plotting)

    def retranslateUi(self, Plotting):
        _translate = QtCore.QCoreApplication.translate
        Plotting.setWindowTitle(_translate("Plotting", "Построение графиков"))
        self.textEdit.setHtml(_translate("Plotting", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("Plotting", "Create"))
        self.menu.setTitle(_translate("Plotting", "Построение графиков"))
        self.action_3.setText(_translate("Plotting", "Обычный калькулятор"))
        self.action_4.setText(_translate("Plotting", "Инженерный калькулятор"))
        self.action_6.setText(_translate("Plotting", "Физические величины"))
from pyqtgraph import PlotWidget
